name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
     - 'v[0-9]+.[0-9]+'
jobs:
    scan:
        runs-on: ubuntu-latest
        if: success()
        steps: 
          - name: Checkout
            uses: actions/checkout@v2

          - name: Run Trivy vulnerability scanner
            id: trivy
            uses: aquasecurity/trivy-action@master
            with: 
              scan-type: 'fs'
              ignore-unfixed: true
              format: 'table'
              exit-code: '0'
              vuln-type: 'os,library'
              output: 'text.txt'
              severity: 'HIGH'
          
    failed-scan:
      runs-on: ubuntu-latest
      name: failed to scan
      steps:
        - name: Slack Notification
          uses: rtCamp/action-slack-notify@v2
          env:
              SLACK_CHANNEL: general
              SLACK_COLOR: ${{ job.status }} 
              SLACK_ICON: https://github.com/rtCamp.png?size=48
              SLACK_MESSAGE: "failed trivy scan, author:Liu Yangxin"
              SLACK_WEBHOOK: ${{ secrets.TEST_WEBHOOK}}
        
        - name: Send txt scan report
          uses: MeilCli/slack-upload-file@v3
          with:
           slack_token: ${{ secrets.TEST_TOKEN }}
           channel_id: ${{ secrets.TEST_CHANNEL_ID }}
           content: 'file content'
           file_type: 'text'
           file_name: 'text.txt'
           file_path: text.txt
           initial_comment: 'Scan report by Liu Yangxin'

