name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  docker:
            runs-on: ubuntu-latest
            steps:
              -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3
              -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
              -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                     username: ${{ secrets.DOCKERHUB_USERNAME }}
                     password: ${{ secrets.DOCKERHUB_TOKEN }}
              -
                name: Build and push
                uses: docker/build-push-action@v5
                with:
                 push: true
                 tags: user/app:latest
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build an image from docker
        run: 
            docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with: 
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'     
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with: 
          payload: |
           {

              "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "You have a new request:\n*<fakeLink.toEmployeeProfile.com|Fred Enriquez - New device request>*"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Type:*\nComputer (laptop)"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*When:*\nSubmitted Aut 10"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Last Update:*\nMar 10, 2015 (3 years, 5 months)"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Reason:*\nAll vowel keys aren't working."
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Specs:*\n\"Cheetah Pro 15\" - Fast, really fast\""
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "emoji": true,
                      "text": "Approve"
                    },
                    "style": "primary",
                    "value": "click_me_123"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "emoji": true,
                      "text": "Deny"
                    },
                    "style": "danger",
                    "value": "click_me_123"
                  }
                ]
              }
            ]
           }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}




            