name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
     - 'v[0-9]+.[0-9]+'
jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    name: Scan the code base for vulnerabilities
    if: ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        id: scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-report.txt'
          exit-code: "1"
          severity: CRITICAL 
          # severity: CRITICAL  

      - name: Scan failed send notification to slack
        if: ${{ failure() && steps.scan.conclusion == 'failure' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_COLOR: ${{ job.status }} 
          SLACK_MESSAGE: 'Failed trivy scan,see uploaded report'
          SLACK_TITLE: Scan failed - Zhao Yinjie
          SLACK_USERNAME: DipSA_CICD
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: slack send trivy scan reports
        if: ${{ failure() && steps.scan.conclusion == 'failure' }}
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'trivy-report.txt'
          initial_comment: 'Scan report by '
  docker:
      runs-on: ubuntu-latest
      needs: trivy-scan
      if: success()
      permissions:
        contents: read
        packages: write
        id-token: write
      steps:
        - name: set up qemu
          uses: docker/setup-qemu-action@v3
        - name: set up docker buid
          uses: docker/setup-buildx-action@v3
        - name: login
          uses: docker/login-action@v3
          with: 
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with: 
            push: true
            tags: liuyangxin/newone:${{ github.sha }}
        - name: Install cosign
          uses: sigstore/cosign-installer@v3.1.1
          with: 
            cosign-release: 'v2.2.0'
        - name: Sign Image
          run: |
              cosign sign --yes --key env://COSIGN_PRIVATE_KEY liuyangxin/newone:${{ github.sha }}
          env: 
            COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
            COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        - name: Slack Notification
          uses: rtCamp/action-slack-notify@v2
          env:
                SLACK_CHANNEL: general
                SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
                SLACK_ICON: https://github.com/rtCamp.png?size=48
                SLACK_MESSAGE: "Name:\nMatribulation:\nEmail:@gmail.com\nGit:https://github.com/idealoverr/Fortune\nImage:https://hub.docker.com/repository/docker/liuyangxin/newone/general"
                SLACK_TITLE: Message 
                SLACK_WEBHOOK: ${{ secrets.TEST_WEBHOOK}}
          



      

           









            