name: Some one is learning workflow
on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'
jobs:
  trivy-scan-code:
    runs-on: ubuntu-latest
    name: Scan the code base for vulnerabilities
    if: ${{ !startsWith(github.event.head_commit.message,'#NORUN') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        id: scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'output.txt'
          exit-code: "1"
          severity: 'HIGH' 
      - name: Scan failed then send notification
        if: ${{ failure()&&steps.scan.conclusion == 'failure'}}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_COLOR: ${{ job.status }} 
          SLACK_MESSAGE: 'Failed trivy scan, please see report'
          SLACK_TITLE: Scan failed
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: slack send trivy scan reports
        if: ${{ failure()&&steps.scan.conclusion == 'failure' }}
        uses: MeilCli/slack-upload-file@v3
        with:
           slack_token: ${{ secrets.SLACK_TOKEN }}
           channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
           file_path: 'output.txt'
           initial_comment: 'Scan report by Liu Yangin'
  build_and_push:
    runs-on: ubuntu-latest
    needs: trivy-scan-code
    if: success()
    permissions:
      contents: read
      packages: write
      id-token: write 
    steps:
      - name: Set up qem
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          push: true
          tags: liuyangxin/newone:${{ github.sha }}          
      - name: Cosign
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: 'v2.2.0' 
      - name: Sign image
        run: |
              cosign sign --yes --key env://COSIGN_PRIVATE_KEY liuyangxin/newone:${{ github.sha }}
        env:
           COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
           COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      - name: Slack Notification
        id: slack_success
        uses: rtCamp/action-slack-notify@v2
        env:
           SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
           SLACK_COLOR: ${{ job.status }} 
           SLACK_MESSAGE: "Name:Liu Yangxin\nMatribulation:E1221833\nEmail:e1221833@u.nus.edu\nGit:https://github.com/idealoverr/Fortune\nImage:https://hub.docker.com/repository/docker/liuyangxin/newone/general"
           SLACK_TITLE: Message  
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          



      

           









            
